### ISSUE TITLE
API Cost hidden when switching to Ollama/VS Code LM API

### ISSUE THREAD

**Issue by mrexodia** [cline/cline#2106]
### What happened?

In my workflow I often plan with a paid model and then use my Copilot Pro subscription via the LM API to act, until I hit a rate limit. When switching to a provider that does not have a cost, the cost disappears completely even if some of the chats had a cost.

### Steps to reproduce

1. Plan with LiteLLM
2. Switch to Ollama/VS Code LM API
3. The total cost disappears

### Relevant API REQUEST output

```shell

```

### Operating System

Windows 10

### Cline Version

3.5.1

### Additional context

![Image](https://github.com/user-attachments/assets/0a076e50-9c92-4901-a618-3ba3fa7324bc)

![Image](https://github.com/user-attachments/assets/0c15a67f-9eed-4f5b-a867-8155d49502b8)

**Comment by gyasi87** [comment]
Ollama is local right? so there shouldn't be any cost.

**Comment by mrexodia** [comment]
> Ollama is local right? so there shouldn't be any cost.

No offense, but you should read the description better…

**Comment by dcbartlett** [comment]
The reason this happens is actually because Ollama is marked as a "no cost" provider.  I'll chat with our UX team and Saoud about the best way to present this.  I definitely understand wanting to know the total cost for the conversation, but the way it's currently designed, that total cost is based on the currently selected model.  We will need to re-factor everything for this to show the cost incurred based on previous calls.

**Comment by mrexodia** [comment]
For me the cost accumulates fine if I switch to a different paid model though? I think setting the cost as 0.0 for free models and hiding the cost when it's 0 would solve the problem. I might take a stab at it later.

**Comment by sammcj** [comment]
FYI the cost tracking using LiteLLM with Cline still seems to be an issue. It always shows as $0 despite LiteLLM exposing the correct model costs.

**Comment by mrexodia** [comment]
Everything works fine for me locally:

<img width="271" alt="Image" src="https://github.com/user-attachments/assets/4be5d03c-4426-480f-8537-bf023872fd18" />

This is with the latest LiteLLM stable v1.72.2

**Comment by sammcj** [comment]
Interesting, so you're running LiteLLM proxy with user keys for the configured models?

**Comment by mrexodia** [comment]
Yeah, I run `litellm[proxy]` configured like this:

```yaml
general_settings:
  telemetry: false
  master_key: sk-secret
  database_url: "postgresql://litellm:password@postgres:5432/litellm"
  store_model_in_db: true
  store_prompts_in_spend_logs: true

litellm_settings:
  s3_callback_params:
    s3_bucket_name: "litellm"
    s3_aws_access_key_id: "access_key"
    s3_aws_secret_access_key: "secret_key"
    s3_endpoint_url: "http://openmediavault:9000"
    s3_region_name: "us-east-1"
    s3_use_ssl: false
  success_callback: ["s3"]
  failure_callback: ["s3"]
```

**Comment by ross-w** [comment]
Issue with LiteLLM cost tracking is likely due to https://github.com/cline/cline/pull/2403#issuecomment-2769741941 (public vs litellm model names)

**Comment by sammcj** [comment]
Someone pointed out to me today that the LiteLLM cost tracking which does not work in Cline - does work in Roo Code.

Perhaps there's some logic that could be borrowed to fix this?

<img width="1126" height="1687" alt="Image" src="https://github.com/user-attachments/assets/aaf98a93-952b-4322-ad6b-992e853c3578" />

<img width="588" height="363" alt="Image" src="https://github.com/user-attachments/assets/754b1719-17f0-4c59-8b0e-18593a55b500" />

**Comment by mrexodia** [comment]
I implemented this feature a few months ago and it was working fine: https://github.com/cline/cline/pull/2403

**Comment by sammcj** [comment]
@mrexodia I can confirm it doesn't work across the company I work with and at least 3 of our clients that use LiteLLM as their LLM API gateway.

On the PR you linked, I see someone else commented stating it didn't work and suggested that the PR may not properly parse litellm_params.model (which is the model we care about for billing): https://github.com/cline/cline/pull/2403#issuecomment-2769741941

In the debug tools I can see Cline continuously throwing this error:

```
  ERR [Extension Host] Error calculating spend: Bad Request

	error | @ | log.ts:460
	-- | -- | --
  | error | @ | log.ts:565
  | error | @ | logService.ts:51
  | Nds | @ | remoteConsoleUtil.ts:58
  | $logExtensionHostMessage | @ | mainThreadConsole.ts:38
  | S | @ | rpcProtocol.ts:458
  | Q | @ | rpcProtocol.ts:443
  | M | @ | rpcProtocol.ts:373
  | L | @ | rpcProtocol.ts:299
  | (anonymous) | @ | rpcProtocol.ts:161
  | C | @ | event.ts:1219
  | fire | @ | event.ts:1250
  | fire | @ | ipc.net.ts:652
  | l.onmessage | @ | localProcessExtensionHost.ts:382
```

<img width="891" height="183" alt="Image" src="https://github.com/user-attachments/assets/616cb8cc-1d20-48b2-95d4-3769d3d72ccf" />

Example model configuration:

```yaml
# LiteLLM Proxy (LLM API Gateway) Configuration

model_list:
  ### Claude Sonnet 4 Load Balanced Across Global Regions ###

  # Claude 4.0 Sonnet (Global) us-west-2
  - model_name: global-claude-4.0-sonnet
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_region_name: us-west-2
      aws_session_name: litellm
    model_info:
      metadata: "🌎 🤖 💰💰💰 Claude Sonnet 4.0 (using non-Australian regions) - Latest Generation, powerful (and expensive) model, most useful for Agentic Coding"

  # Claude 4.0 Sonnet (Global) us-east-1
  - model_name: global-claude-4.0-sonnet
    litellm_params:
      model: bedrock/converse/us.anthropic.claude-sonnet-4-20250514-v1:0
      aws_region_name: us-east-1
      aws_session_name: litellm
    model_info:
      metadata: "🌎 🤖 💰💰💰 Claude Sonnet 4.0 (using non-Australian regions) - Latest Generation, powerful (and expensive) model, most useful for Agentic Coding"

  ### Claude Sonnet 4 Load Balanced Across AU Regions w/ Cross-Region Inference ###

  # Claude 4.0 Sonnet (Cross-Region Inference)
  - model_name: au-cross-region-claude-4.0-sonnet
    litellm_params:
      model: bedrock/converse/apac.anthropic.claude-sonnet-4-20250514-v1:0
      aws_region_name: ap-southeast-2
      aws_session_name: litellm
    model_info:
      metadata: "🌎 🤖 💰💰💰 Claude Sonnet 4.0 (ap-southeast-2 AWS resources, with cross-region inference compute from non-Australian regions) - Latest Generation, powerful (and expensive) model, most useful for Agentic Coding"


# Global LiteLLM settings
litellm_settings:
  drop_params: true
  set_verbose: true
  max_internal_user_budget: 3500 # amount in USD
  max_budget: 3500
  budget_duration: "28d"
  internal_user_budget_duration: "28d" # reset every month
  cache: true
  cache_params:
    type: redis
    ttl: 7200 # Cache entries will expire after 7200 seconds (2 hours)
```

Please let me know if there's any other information I can provide that might be useful.

cc/ @ross-w
