### ISSUE TITLE
Unable to Parse message.content array from Databricks Claude 3.7 Sonnet via LiteLLM Proxy

### ISSUE THREAD

**Issue by shahul398** [cline/cline#3032]
### Issue parsing `message.content` array from Databricks Claude 3.7 Sonnet via LiteLLM Proxy

**Environment:**

* **OS:** macOS Sequoia version 15.1
* **VS Code Version:** 1.99
* **Cline Extension Version:** 3.13
* **LiteLLM Version:** 1.65.4.post1
* **Backend Model:** Claude 3.7 Sonnet (hosted on Azure Databricks)
* **Proxy:** LiteLLM Proxy (running locally, `http://0.0.0.0:4000`)

**Problem Description:**

When using the Cline extension configured to connect to my local LiteLLM proxy, which is forwarding requests to an Azure Databricks-hosted Claude 3.7 Sonnet model, the extension fails to display the model's response and consistently shows the error:

`Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output.`

The LiteLLM proxy successfully receives the request from Cline (when using the correct alias) and successfully communicates with the Databricks backend, retrieves a response, and returns it to Cline. However, Cline appears unable to parse this specific response format.

**Steps to Reproduce:**

1.  Set up LiteLLM proxy with the following configuration (relevant part for the Databricks model):

    ```yaml
    model_list:
      - model_name: claude-3-7-sonnet
        litellm_params:
          model: openai/databricks-claude-3-7-sonnet
          api_base: "https://YOUR_DATABRICKS_URL/serving-endpoints" # Replace with your actual Databricks URL base
          api_key: "YOUR_DATABRICKS_TOKEN" # Replace with your actual Databricks token
          custom_llm_provider: openai
          drop_params: true # Attempted to drop extra params
    general_settings:
      master_key: "sk-1234" # Replace with your LiteLLM master key used in Cline
    ```
2.  Start the LiteLLM proxy: `litellm --config config.yaml`
3.  Configure the VS Code Cline extension using the **"OpenAI API"** mode with the following settings:
    * Base URL: `http://0.0.0.0:4000`
    * API Key: `sk-1234` (Matching LiteLLM `master_key`)
    * Model Name: `claude-3-7-sonnet` (Matching LiteLLM `model_name` alias)
4.  Send a prompt to the model using the Cline extension.

**Expected Behavior:**

The Cline extension should parse the response received from the LiteLLM proxy and display the assistant's message content in the chat window.

**Actual Behavior:**

The Cline extension displays the error message mentioned above.

**Relevant Data:**

* **Problematic Response Structure received by LiteLLM (observed from backend/logs):**
    The response format from the Databricks Claude endpoint, as seen by LiteLLM before returning to Cline, sometimes includes `message.content` as an array, which is suspected to be the cause:

    ```json
    {
      "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
      "choices": [
        {
          "message": {
            "role": "assistant",
            "content": [ // <--- This array structure
              {
                "type": "reasoning",
                "summary": [ // Content omitted for brevity
                  {
                    "type": "summary_text",
                    "text": "...",
                    "signature": "..."
                  }
                ]
              },
              {
                "type": "text",
                "text": "Hello! It looks like you might have sent a test message. Is there something specific I can help you with today? I'm here to answer questions or assist with information on a wide range of topics." // <--- The actual response text is nested here
              }
            ]
          },
          "index": 0,
          "finish_reason": "stop"
        }
      ],
      "usage": { /* ... */ }, // Content omitted for brevity
      "object": "chat.completion",
      "id": "/* ... */", // ID omitted for brevity
      "created": /* ... */ // Timestamp omitted for brevity
    }
    ```
    *(Note: A standard OpenAI chat completion response would have `message.content` as a simple string containing the text.)*

**Troubleshooting Attempted:**

* Confirmed the LiteLLM proxy successfully connects to and receives responses from the Databricks Claude endpoint using direct `curl` commands targeting the LiteLLM proxy (`http://0.0.0.0:4000`), proving the proxy-to-backend connection works.
* Configured `drop_params: true` in the LiteLLM config for this model to remove extraneous parameters, but the issue persists with the `content` array structure.
* Successfully used the Cline extension with the same LiteLLM proxy pointing to an Azure OpenAI GPT-4.5 model (configured in LiteLLM using `model: azure/gpt-45-preview`, `api_base`, `api_key`, `api_version`, and `model_name: gpt-4.5-preview`), which returns `message.content` as a simple string. This confirms the basic Cline-to-LiteLLM connection works correctly for standard OpenAI response formats.

**Request:**

It appears the Cline extension may not be currently equipped to handle the `message.content` field when it is returned as an array containing different content types like `"reasoning"` and `"text"`, as sometimes returned by models like Databricks Claude. Could support be added for parsing `message.content` arrays (specifically extracting the `text` from `type: "text"` objects) or is there a known configuration within Cline to accommodate this?

---

### Steps to reproduce

**Steps to Reproduce:**

1.  Set up LiteLLM proxy with the following configuration (relevant part for the Databricks model):

    ```yaml
    model_list:
      - model_name: claude-3-7-sonnet
        litellm_params:
          model: openai/databricks-claude-3-7-sonnet
          api_base: "https://YOUR_DATABRICKS_URL/serving-endpoints" # Replace with your actual Databricks URL base
          api_key: "YOUR_DATABRICKS_TOKEN" # Replace with your actual Databricks token
          custom_llm_provider: openai
          drop_params: true # Attempted to drop extra params
    general_settings:
      master_key: "sk-1234" # Replace with your LiteLLM master key used in Cline
    ```
2.  Start the LiteLLM proxy: `litellm --config config.yaml`
3.  Configure the VS Code Cline extension using the **"OpenAI API"** mode with the following settings:
    * Base URL: `http://0.0.0.0:4000`
    * API Key: `sk-1234` (Matching LiteLLM `master_key`)
    * Model Name: `claude-3-7-sonnet` (Matching LiteLLM `model_name` alias)
4.  Send a prompt to the model using the Cline extension.

**Expected Behavior:**

The Cline extension should parse the response received from the LiteLLM proxy and display the assistant's message content in the chat window.

**Actual Behavior:**

The Cline extension displays the error message mentioned above.

**Relevant Data:**

* **Problematic Response Structure received by LiteLLM (observed from backend/logs):**
    The response format from the Databricks Claude endpoint, as seen by LiteLLM before returning to Cline, sometimes includes `message.content` as an array, which is suspected to be the cause:

    ```json
    {
      "model": "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
      "choices": [
        {
          "message": {
            "role": "assistant",
            "content": [ // <--- This array structure
              {
                "type": "reasoning",
                "summary": [ // Content omitted for brevity
                  {
                    "type": "summary_text",
                    "text": "...",
                    "signature": "..."
                  }
                ]
              },
              {
                "type": "text",
                "text": "Hello! It looks like you might have sent a test message. Is there something specific I can help you with today? I'm here to answer questions or assist with information on a wide range of topics." // <--- The actual response text is nested here
              }
            ]
          },
          "index": 0,
          "finish_reason": "stop"
        }
      ],
      "usage": { /* ... */ }, // Content omitted for brevity
      "object": "chat.completion",
      "id": "/* ... */", // ID omitted for brevity
      "created": /* ... */ // Timestamp omitted for brevity
    }
    ```
    *(Note: A standard OpenAI chat completion response would have `message.content` as a simple string containing the text.)*

### Relevant API REQUEST output

```shell

```

### Provider/Model

Claude 3.7 Sonnet (hosted on Azure Databricks)

### Operating System

macOS Sequoia version 15.1

### Cline Version

3.13
